server:
  port: ${PORT:8762}

spring:
  application:
    name: containerized-gateway
  logstash:
    server: 192.168.1.102
    port: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    distribution:
      percentiles-histogram.http.server.requests: false
      percentiles.http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999
      sla.http.server.requests: 500ms, 2000ms

zuul:
  prefix: /api/v1
  routes:
    containerized-main:
      path: /backoffice/**
      serviceId: containerized-main
    containerized-accounts:
      path: /account/**
      serviceId: containerized-accounts
    containerized-orders:
      path: /order/**
      serviceId: containerized-orders
    containerized-products:
      path: /product/**
      serviceId: containerized-products

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000